/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Registrant = IDL.Record({
  'id' : IDL.Text,
  'interests' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'email' : IDL.Text,
  'skillLevel' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const UserBadge = IDL.Record({
  'principal' : IDL.Principal,
  'uniqueId' : IDL.Text,
  'badge' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addRegistrant' : IDL.Func([Registrant], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteRegistrant' : IDL.Func([IDL.Principal], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getOrCreateUserBadge' : IDL.Func([], [UserBadge], []),
  'getRegistrant' : IDL.Func([IDL.Principal], [IDL.Opt(Registrant)], ['query']),
  'getUserBadge' : IDL.Func([IDL.Principal], [IDL.Opt(UserBadge)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllRegistrants' : IDL.Func([], [IDL.Vec(Registrant)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchRegistrants' : IDL.Func([IDL.Text], [IDL.Vec(Registrant)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Registrant = IDL.Record({
    'id' : IDL.Text,
    'interests' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'email' : IDL.Text,
    'skillLevel' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const UserBadge = IDL.Record({
    'principal' : IDL.Principal,
    'uniqueId' : IDL.Text,
    'badge' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addRegistrant' : IDL.Func([Registrant], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteRegistrant' : IDL.Func([IDL.Principal], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getOrCreateUserBadge' : IDL.Func([], [UserBadge], []),
    'getRegistrant' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(Registrant)],
        ['query'],
      ),
    'getUserBadge' : IDL.Func([IDL.Principal], [IDL.Opt(UserBadge)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllRegistrants' : IDL.Func([], [IDL.Vec(Registrant)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchRegistrants' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Registrant)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };