/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Registrant {
  'id' : string,
  'cryptoAddress' : [] | [string],
  'interests' : Array<string>,
  'instagram' : [] | [string],
  'name' : string,
  'email' : string,
  'website' : [] | [string],
  'facebook' : [] | [string],
  'skillLevel' : string,
  'telegram' : [] | [string],
}
export interface UserBadge {
  'principal' : Principal,
  'uniqueId' : string,
  'badge' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addRegistrant' : ActorMethod<[Registrant], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteRegistrant' : ActorMethod<[Principal], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getOrCreateUserBadge' : ActorMethod<[], UserBadge>,
  'getRegistrant' : ActorMethod<[Principal], [] | [Registrant]>,
  'getTotalNumberOfRegistrants' : ActorMethod<[], bigint>,
  'getUserBadge' : ActorMethod<[Principal], [] | [UserBadge]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllRegistrants' : ActorMethod<[], Array<Registrant>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchRegistrants' : ActorMethod<[string], Array<Registrant>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];