/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserBadge {
    principal: Principal;
    uniqueId: string;
    badge: string;
}
export interface PublicRegistrant {
    id: string;
    cryptoAddress?: string;
    interests: Array<string>;
    instagram?: string;
    name: string;
    sector: Sector;
    email: string;
    website?: string;
    facebook?: string;
    skillLevel: string;
    telegram?: string;
}
export interface Registrant {
    id: string;
    cryptoAddress?: string;
    interests: Array<string>;
    instagram?: string;
    name: string;
    sector: Sector;
    email: string;
    website?: string;
    facebook?: string;
    isPublic: boolean;
    skillLevel: string;
    telegram?: string;
}
export interface UserProfile {
    name: string;
}
export enum Sector {
    professionLiberal = "professionLiberal",
    etudiant = "etudiant",
    artiste = "artiste",
    aucuneActivite = "aucuneActivite",
    sportif = "sportif",
    fonctionnaire = "fonctionnaire",
    services = "services",
    marchand = "marchand",
    association = "association"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addRegistrant(registrant: Registrant): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteRegistrant(principal: Principal): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getOrCreateUserBadge(): Promise<UserBadge>;
    getPublicRegistrantsBySector(optSector: Sector | null): Promise<Array<PublicRegistrant>>;
    getPublicRegistrantsCountBySector(optSector: Sector | null): Promise<bigint>;
    getRegistrant(principal: Principal): Promise<Registrant | null>;
    getTotalNumberOfRegistrants(): Promise<bigint>;
    getUserBadge(principal: Principal): Promise<UserBadge | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listAllRegistrants(): Promise<Array<Registrant>>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchRegistrants(searchTerm: string): Promise<Array<Registrant>>;
}
import type { PublicRegistrant as _PublicRegistrant, Registrant as _Registrant, Sector as _Sector, UserBadge as _UserBadge, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addRegistrant(arg0: Registrant): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addRegistrant(to_candid_Registrant_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRegistrant(to_candid_Registrant_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteRegistrant(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRegistrant(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRegistrant(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrCreateUserBadge(): Promise<UserBadge> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrCreateUserBadge();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrCreateUserBadge();
            return result;
        }
    }
    async getPublicRegistrantsBySector(arg0: Sector | null): Promise<Array<PublicRegistrant>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicRegistrantsBySector(to_candid_opt_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicRegistrantsBySector(to_candid_opt_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublicRegistrantsCountBySector(arg0: Sector | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicRegistrantsCountBySector(to_candid_opt_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicRegistrantsCountBySector(to_candid_opt_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getRegistrant(arg0: Principal): Promise<Registrant | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRegistrant(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRegistrant(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTotalNumberOfRegistrants(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalNumberOfRegistrants();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalNumberOfRegistrants();
            return result;
        }
    }
    async getUserBadge(arg0: Principal): Promise<UserBadge | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserBadge(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserBadge(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAllRegistrants(): Promise<Array<Registrant>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllRegistrants();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllRegistrants();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchRegistrants(arg0: string): Promise<Array<Registrant>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchRegistrants(arg0);
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchRegistrants(arg0);
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_PublicRegistrant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PublicRegistrant): PublicRegistrant {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Registrant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Registrant): Registrant {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Sector_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Sector): Sector {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Registrant]): Registrant | null {
    return value.length === 0 ? null : from_candid_Registrant_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserBadge]): UserBadge | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    cryptoAddress: [] | [string];
    interests: Array<string>;
    instagram: [] | [string];
    name: string;
    sector: _Sector;
    email: string;
    website: [] | [string];
    facebook: [] | [string];
    skillLevel: string;
    telegram: [] | [string];
}): {
    id: string;
    cryptoAddress?: string;
    interests: Array<string>;
    instagram?: string;
    name: string;
    sector: Sector;
    email: string;
    website?: string;
    facebook?: string;
    skillLevel: string;
    telegram?: string;
} {
    return {
        id: value.id,
        cryptoAddress: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.cryptoAddress)),
        interests: value.interests,
        instagram: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.instagram)),
        name: value.name,
        sector: from_candid_Sector_n15(_uploadFile, _downloadFile, value.sector),
        email: value.email,
        website: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.website)),
        facebook: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.facebook)),
        skillLevel: value.skillLevel,
        telegram: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.telegram))
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    cryptoAddress: [] | [string];
    interests: Array<string>;
    instagram: [] | [string];
    name: string;
    sector: _Sector;
    email: string;
    website: [] | [string];
    facebook: [] | [string];
    isPublic: boolean;
    skillLevel: string;
    telegram: [] | [string];
}): {
    id: string;
    cryptoAddress?: string;
    interests: Array<string>;
    instagram?: string;
    name: string;
    sector: Sector;
    email: string;
    website?: string;
    facebook?: string;
    isPublic: boolean;
    skillLevel: string;
    telegram?: string;
} {
    return {
        id: value.id,
        cryptoAddress: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.cryptoAddress)),
        interests: value.interests,
        instagram: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.instagram)),
        name: value.name,
        sector: from_candid_Sector_n15(_uploadFile, _downloadFile, value.sector),
        email: value.email,
        website: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.website)),
        facebook: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.facebook)),
        isPublic: value.isPublic,
        skillLevel: value.skillLevel,
        telegram: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.telegram))
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    professionLiberal: null;
} | {
    etudiant: null;
} | {
    artiste: null;
} | {
    aucuneActivite: null;
} | {
    sportif: null;
} | {
    fonctionnaire: null;
} | {
    services: null;
} | {
    marchand: null;
} | {
    association: null;
}): Sector {
    return "professionLiberal" in value ? Sector.professionLiberal : "etudiant" in value ? Sector.etudiant : "artiste" in value ? Sector.artiste : "aucuneActivite" in value ? Sector.aucuneActivite : "sportif" in value ? Sector.sportif : "fonctionnaire" in value ? Sector.fonctionnaire : "services" in value ? Sector.services : "marchand" in value ? Sector.marchand : "association" in value ? Sector.association : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PublicRegistrant>): Array<PublicRegistrant> {
    return value.map((x)=>from_candid_PublicRegistrant_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Registrant>): Array<Registrant> {
    return value.map((x)=>from_candid_Registrant_n18(_uploadFile, _downloadFile, x));
}
function to_candid_Registrant_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Registrant): _Registrant {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Sector_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Sector): _Sector {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Sector | null): [] | [_Sector] {
    return value === null ? candid_none() : candid_some(to_candid_Sector_n3(_uploadFile, _downloadFile, value));
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    cryptoAddress?: string;
    interests: Array<string>;
    instagram?: string;
    name: string;
    sector: Sector;
    email: string;
    website?: string;
    facebook?: string;
    isPublic: boolean;
    skillLevel: string;
    telegram?: string;
}): {
    id: string;
    cryptoAddress: [] | [string];
    interests: Array<string>;
    instagram: [] | [string];
    name: string;
    sector: _Sector;
    email: string;
    website: [] | [string];
    facebook: [] | [string];
    isPublic: boolean;
    skillLevel: string;
    telegram: [] | [string];
} {
    return {
        id: value.id,
        cryptoAddress: value.cryptoAddress ? candid_some(value.cryptoAddress) : candid_none(),
        interests: value.interests,
        instagram: value.instagram ? candid_some(value.instagram) : candid_none(),
        name: value.name,
        sector: to_candid_Sector_n3(_uploadFile, _downloadFile, value.sector),
        email: value.email,
        website: value.website ? candid_some(value.website) : candid_none(),
        facebook: value.facebook ? candid_some(value.facebook) : candid_none(),
        isPublic: value.isPublic,
        skillLevel: value.skillLevel,
        telegram: value.telegram ? candid_some(value.telegram) : candid_none()
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Sector): {
    professionLiberal: null;
} | {
    etudiant: null;
} | {
    artiste: null;
} | {
    aucuneActivite: null;
} | {
    sportif: null;
} | {
    fonctionnaire: null;
} | {
    services: null;
} | {
    marchand: null;
} | {
    association: null;
} {
    return value == Sector.professionLiberal ? {
        professionLiberal: null
    } : value == Sector.etudiant ? {
        etudiant: null
    } : value == Sector.artiste ? {
        artiste: null
    } : value == Sector.aucuneActivite ? {
        aucuneActivite: null
    } : value == Sector.sportif ? {
        sportif: null
    } : value == Sector.fonctionnaire ? {
        fonctionnaire: null
    } : value == Sector.services ? {
        services: null
    } : value == Sector.marchand ? {
        marchand: null
    } : value == Sector.association ? {
        association: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
